arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - joint_a1
     - joint_a2
     - joint_a3
     - joint_a4
     - joint_a5
     - joint_a6
  constraints:
      goal_time: 0.05
      stopped_velocity_tolerance: 0.01
      joint_a1: {trajectory: 0.1, goal: 0.05}
      joint_a2: {trajectory: 0.1, goal: 0.05}
      joint_a3: {trajectory: 0.1, goal: 0.05}
      joint_a4: {trajectory: 0.1, goal: 0.05}
      joint_a5: {trajectory: 0.1, goal: 0.05}
      joint_a6: {trajectory: 0.1, goal: 0.05}
  stop_trajectory_duration: 0.1
  allow_partial_joints_goal: true
  gains:
    joint_a1: {p: 100,  d: 1, i: 1, i_clamp: 1}
    joint_a2: {p: 100,  d: 1, i: 1, i_clamp: 1}
    joint_a3: {p: 100,  d: 1, i: 1, i_clamp: 1}
    joint_a4: {p: 100,  d: 1, i: 1, i_clamp: 1}
    joint_a5: {p: 100,  d: 1, i: 1, i_clamp: 1}
    joint_a6: {p: 100,  d: 1, i: 1, i_clamp: 1}
