<?xml version="1.0"?>
<robot name="x6" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="base_height" value=".008"/>
  <xacro:property name="base_radius" value=".05"/>
  <xacro:property name="j1_length" value=".276"/>
  <!--0.284 to base plate-->
  <xacro:property name="j2_length" value=".307"/>
  <xacro:property name="j3_length" value=".130"/>
  <xacro:property name="j4_length" value=".181"/>
  <xacro:property name="j5_length" value=".126"/>
  <xacro:property name="j5_offset" value=".018"/>
  <xacro:property name="j6_length" value=".012"/>
  <xacro:property name="pi" value="3.1415926536"/>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}"/>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </xacro:macro>

  <macro name="x6_arm" params="parent *origin">
    <link name="x6_base_link">
      <visual>
        <geometry>
          <!-- <mesh filename="package://x6_description/meshes/x6_common/x6_link_0_gnd.dae"/> -->
          <cylinder radius="${base_radius}" length="${base_height}"/>
        </geometry>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <material name="blue">
          <color rgba="0 0 .8 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${base_radius}" length="${base_height}"/>
          <!-- <mesh filename="package://x6_description/meshes/x6_common/x6_link_0_gnd.stl"/> -->
        </geometry>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      </collision>
      <xacro:default_inertial mass="0.1"/>
    </link>
    <gazebo reference="x6_base_link">
      <selfCollide>true</selfCollide>
      <material>x6_material/Grey</material>
      <!--<material>HLUGV/Green</material>-->
    </gazebo>
    <link name="x6_link1">
      <visual>
        <geometry>
          <mesh filename="package://x6_description/meshes/x6_common/x6_link_1.dae"/>
          <!--                    <box size="${j1_x} ${j1_y} ${j1_z}" />-->
        </geometry>
        <origin xyz="0 0 ${-base_height}" rpy="0 0 ${pi/2}"/>
        <material name="green">
          <color rgba="0.9 0.9 0.9 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://x6_description/meshes/x6_common/x6_link_1.stl"/>
          <!--<box size="${j1_x} ${j1_y} ${j1_z}" />-->
        </geometry>
        <origin xyz="0 0 ${-base_height}" rpy="0 0 ${pi/2}"/>
      </collision>
      <xacro:default_inertial mass="3"/>
    </link>
    <gazebo reference="x6_link1">
      <selfCollide>true</selfCollide>
      <material>x6_material/White</material>
      <!--<material>Gazebo/Blue</material>-->
    </gazebo>
    <link name="x6_link2">
      <visual>
        <geometry>
          <mesh filename="package://x6_description/meshes/x6_common/x6_link_2.dae"/>
          <!--<mesh filename="package://katana_description/meshes/katana/katana_internal_controlbox.stl" />-->
        </geometry>
        <!--<origin xyz="${j2_length/2 - j2_overhang_rear/2 } 0 0" rpy="0 ${pi/2} 0"/>-->
        <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi}"/>
        <material name="red">
          <color rgba="0.6 0.6 0.6 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://x6_description/meshes/x6_common/x6_link_2.stl"/>
          <!--<cylinder radius="0.02" length="${j2_length}" />-->
        </geometry>
        <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi}"/>
      </collision>
      <xacro:default_inertial mass="0.5"/>
    </link>
    <gazebo reference="x6_link2">
      <selfCollide>true</selfCollide>
      <material>x6_material/Grey</material>
      <!--<material>HLUGV/Green</material>-->
    </gazebo>
    <link name="x6_link3">
      <visual>
        <geometry>
          <mesh filename="package://x6_description/meshes/x6/x6_link_3.dae"/>
          <!--<cylinder radius="0.02" length="${j3_length}" />-->
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
        <material name="red">

                </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://x6_description/meshes/x6/x6_link_3.stl"/>
          <!--  <cylinder radius="0.02" length="${j3_length}" />-->
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
      </collision>
      <xacro:default_inertial mass="0.1"/>
    </link>
    <gazebo reference="x6_link3">
      <selfCollide>true</selfCollide>
      <material>x6_material/Grey</material>
      <!--<material>HLUGV/Green</material>-->
    </gazebo>
    <link name="x6_link4">
      <visual>
        <geometry>
          <mesh filename="package://x6_description/meshes/x6/x6_link_4.dae"/>
          <!--                    <cylinder radius="0.002" length="0.001" />-->
        </geometry>
        <origin xyz="0 0 ${-j3_length + 0.03}" rpy="${pi} 0 0"/>
        <material name="red">

                </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://x6_description/meshes/x6/x6_link_4.stl"/>
          <!--<cylinder radius="0.02" length="${j4_length}" />-->
        </geometry>
        <origin xyz="0 0 ${-j3_length + 0.03}" rpy="${pi} 0 0"/>

      </collision>
      <xacro:default_inertial mass="0.01"/>
    </link>
    <gazebo reference="x6_link5">
      <selfCollide>true</selfCollide>
      <material>x6_material/Grey</material>
      <!--<material>HLUGV/Green</material>-->
    </gazebo>
    <link name="x6_link5">
      <visual>
        <geometry>
          <mesh filename="package://x6_description/meshes/x6_common/x6_link_4_0120.dae"/>
          <!--  <cylinder radius="0.02" length="${j4_length}" />-->
        </geometry>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 0"/>
        <material name="red">

                </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://x6_description/meshes/x6_common/x6_link_4_0120.stl"/>
          <!--<cylinder radius="0.02" length="${j4_length}" />-->
        </geometry>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 0"/>
      </collision>
      <xacro:default_inertial mass="0.01"/>
    </link>
    <gazebo reference="x6_link5">
      <selfCollide>true</selfCollide>
      <material>x6_material/Grey</material>
      <!--<material>HLUGV/Green</material>-->
    </gazebo>
    <link name="x6_link6">
      <visual>
        <geometry>
          <mesh filename="package://x6_description/meshes/x6/x6_link_6.dae"/>
          <!--<cylinder radius="0.002" length="0.001" />-->
        </geometry>
        <origin xyz="0 0 -0.036" rpy="0 0 0"/>
        <material name="red">

      </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://x6_description/meshes/x6/x6_link_6.stl"/>
          <!--<cylinder radius="0.002" length="0.001" />-->
        </geometry>
        <origin xyz="0 0 -0.036" rpy="0 0 0"/>
      </collision>
      <xacro:default_inertial mass="0.01"/>
    </link>
    <gazebo reference="x6_link6">
      <selfCollide>true</selfCollide>
      <material>x6_material/Grey</material>
      <!--<material>HLUGV/Green</material>-->
    </gazebo>

    <link name="x6_toolframe">
      <visual>
        <geometry>
          <mesh filename="package://x6_description/meshes/x6_common/x6_rot_racket.dae"/>
	  <!-- <cylinder radius="0.08" length="0.01" /> -->
        </geometry>
	<origin xyz="-0.0015 0 0.01" rpy="0 -${pi/2} ${pi}"/>
	<!-- <origin xyz="-0.0215 0 0.01" rpy="0 0 0"/> -->
        <material name="blue">
          <color rgba="0 0 .8 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <!-- <mesh filename="package://x6_description/meshes/x6_common/x6_rot_racket.stl"/> -->
          <cylinder radius="0.08" length="0.01" />
        </geometry>
	<!--<origin xyz="-0.0015 0 0.01" rpy="0 -${pi/2} ${pi}"/> -->
	<origin xyz="-0.0215 0 0.01" rpy="0 0 0"/>

        <surface>
          <contact>
            <ode>
              <kp>1e+08</kp>
              <kd>10000</kd>
            </ode>
          </contact>
          <friction>
            <ode>
              <mu>0</mu>
              <mu2>0</mu2>
            </ode>
          </friction>
        </surface>

      </collision>
      <xacro:default_inertial mass="0.01"/>
    </link>
     <gazebo reference="x6_toolframe">
      <selfCollide>true</selfCollide>
      <material>Gazebo/Grey</material>
    </gazebo>

    <joint name="x6_base_joint" type="fixed">
      <insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="x6_base_link"/>
    </joint>
    <joint name="joint1" type="revolute">
      <parent link="x6_base_link"/>
      <child link="x6_link1"/>
      <axis xyz="0 0 1"/>
      <origin xyz="0 0 ${base_height}"/>
      <limit effort="50.0" lower="-2.53" upper="2.53" velocity="2.617"/>
      <!-- TODO: give correct effort limits -->
      <dynamics damping="1.0" friction="1.0"/>
    </joint>
    <joint name="joint2" type="revolute">
      <parent link="x6_link1"/>
      <child link="x6_link2"/>
      <axis xyz="0 0 1"/>
      <origin xyz="0 0 ${j1_length}" rpy="${pi/2} 0 0"/>
      <limit effort="50.0" lower="-2.181" upper="2.0071" velocity="2.617"/>
      <dynamics damping="1.0" friction="1.0"/>
    </joint>
    <joint name="joint3" type="revolute">
      <parent link="x6_link2"/>
      <child link="x6_link3"/>
      <axis xyz="0 0 1 "/>
      <origin xyz="0 ${j2_length} 0" rpy="0 0 ${pi/2}"/>
      <limit effort="30.0" lower="-2.007" upper="2.007" velocity="2.617"/>
      <dynamics damping="1.0" friction="1.0"/>
    </joint>
    <joint name="joint4" type="revolute">
      <parent link="x6_link3"/>
      <child link="x6_link4"/>
      <axis xyz="0 0 1"/>
      <origin xyz="0 0 0.0" rpy="${pi/2} 0 ${-pi/2}"/>
      <limit effort="30.0" lower="-1.83" upper="1.83" velocity="2.617"/>
      <!-- TODO: give correct effort limits -->
      <dynamics damping="1.0" friction="1.0"/>
    </joint>
    <!-- fixed because of Robot malfunction -->
    <joint name="joint5" type="revolute">
    <!--<joint name="joint5" type="fixed">-->
      <parent link="x6_link4"/>
      <child link="x6_link5"/>
      <axis xyz="0 0 1"/>
      <origin xyz="0 0 ${-j3_length - j4_length}" rpy="${-pi/2} 0 0"/>
      <!--<origin xyz="0 0 ${-j3_length - j4_length}" rpy="${-pi/2} ${pi/2} 0"/>-->
      <limit effort="30.0" lower="-1.57" upper="1.57" velocity="2.617"/>
      <!-- <limit effort="0.1" lower="0.01" upper="0.01" velocity="0.1"/> -->
      <!--<dynamics damping="1.0" friction="1.0"/>-->
    </joint>
    <joint name="joint6" type="revolute">
      <parent link="x6_link5"/>
      <child link="x6_link6"/>
      <axis xyz="0 0 1"/>
      <origin xyz="0 ${j5_length} ${j5_offset}" rpy="${-pi/2} 0 0"/>
      <limit effort="10.0" lower="-1.57" upper="1.57" velocity="2.617"/>
      <!-- TODO: give correct effort limits -->
      <dynamics damping="1.0" friction="1.0"/>
    </joint>
    <joint name="tool_frame" type="fixed">
      <parent link="x6_link6"/>
      <child link="x6_toolframe"/>
      <axis xyz="0 0 1"/>
      <!-- <origin xyz="0 ${j6_length} 0" rpy="0 0 ${pi/2}"/> -->
      <origin xyz="0 ${j6_length} 0.11" rpy="${pi} -${pi/2} ${3*pi/2}"/>
    </joint>

    <transmission name="joint1_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="joint1">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
    </transmission>

    <transmission name="joint2_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="joint2">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    </transmission>

    <transmission name="joint3_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="joint3">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
    </transmission>

    <transmission name="joint4_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="joint4">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
    </transmission>

    <transmission name="joint5_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="joint5">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
    </transmission>

    <transmission name="joint6_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="joint6">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
    </transmission>

    <!--    <gazebo reference="x6_toolframe">
      <sensor:camera name="finger_tip_camera_sensor">
        <imageSize>640 480</imageSize>
        <imageFormat>R8G8B8</imageFormat>
        <hfov>90</hfov>
        <nearClip>0.01</nearClip>
        <farClip>100</farClip>
        <updateRate>20.0</updateRate>
        <controller:gazebo_ros_camera name="finger_tip_camera_controller" plugin="libgazebo_ros_camera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>20.0</updateRate>
          <imageTopicName>finger_tip_cam/image</imageTopicName>
          <frameName>x6_toolframe</frameName>
          <interface:camera name="finger_tip_camera_iface" />
        </controller:gazebo_ros_camera>
      </sensor:camera>
      <turnGravityOff>true</turnGravityOff>
      <material>PR2/Blue</material>
    </gazebo>-->
    <!--        <gazebo>
              <controller:gazebo_ros_controller_manager name="gazebo_ros_controller_manager" plugin="libgazebo_ros_controller_manager.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>100.0</updateRate>
                <interface:audio name="gazebo_ros_controller_manager_dummy_iface_x6" />
              </controller:gazebo_ros_controller_manager>

            </gazebo>-->
  </macro>
</robot>
